#ifndef POLYGON_MATHEMATICS_TYPE_DEFINITIONS_H
#define POLYGON_MATHEMATICS_TYPE_DEFINITIONS_H

namespace polygon
{
	// Typedefs:
	typedef float Float32;
	typedef bool Bool32;
	typedef int Int32;
	typedef unsigned int Uint32;
	typedef char Char32;
}

// Defines:
#define POLYGON_NULL 0
#define POLYGON_PI 3.14159265358979323846
#define POLYGON_RADIANS_TO_DEGREES 180 / POLYGON_PI
#define POLYGON_DEGREES_TO_RADIANS POLYGON_PI / 180

#endif POLYGON_MATHEMATICS_TYPE_DEFINITIONS_H // !POLYGON_MATHEMATICS_TYPE_DEFINITIONS_H